### ISSUE TITLE
Cannot deploy snapshot version to OSS Sonatype repository

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/couchbase-cache#37]
In currently, `after_success.sh` deploy snapshot version when use JDK 6. We should be change to deploy when use JDK 8(`openjdk8`).

**Comment by hazendaz** [comment]
travis file is corrected.  Additional issue with 401 pushing to sonatype so possibly just needs updated ruby gem.

coveralls was an issue too and only needed turned on.

**Comment by hazendaz** [comment]
[ci] Rewrite secure tokens

Successfully deployed SNAPSHOT artifacts to Sonatype under Travis job 99.2

Successfully ran coveralls under Travis job 99.2
